Leetcode questions done on Dec 25
asxzhy/Leetcode pull request #24
Opened 2020-12-26 03:39 UTC by asxzhy

2020-12-28 02:08 UTC, asxzy requested changes

2020-12-28 02:08 UTC, asxzy commented on leetcode/question_111/solution_1.py
> +            return self.minDepth(root.left) + 1
did you submit and check this solution? the recursive function is not called properly

2020-12-28 02:08 UTC, asxzy commented on leetcode/question_111/solution_2.py
> +print(s.minDepth(e))
same problem here

2020-12-28 02:08 UTC, asxzy commented on leetcode/question_112/solution_2.py
> +        def find_sum(node, total):
indicate types for arguments is recommended.

2020-12-29 22:09 UTC, yi-nlmatics approved these changes

2020-12-29 22:09 UTC, asxzy approved these changes

2020-12-29 22:10 UTC, merged